### PR TITLE
Microg Post

### PR DESCRIPTION
**Pull request by Jorbay**
MicroG update post for week before trip to Houston

### CODE REVIEW

**Comment by leee** [comment]
-1, revert.

Correct line 23 of the post.

**Comment by jakehlee** [comment]
Image sizes broken, not all news showing up. Investigating.

**Comment by jakehlee** [comment]
Oh Alpha branch is missing a bunch of CSS and older posts and images. @Jorbay remember to pull from master (press the sync button) before you make changes.

**Comment by Jorbay** [comment]
Oi, sorry for the mistake. Thanks for the corrections guys.

**Pull request merged**
